"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

sys.setrecursiondepth(8000) # To Fix py2app's recursion bug.

APP = ['Rosetta.py']
DATA_FILES = []
OPTIONS = {'iconfile':'icon.icns',
			'includes': ['sip','PyQt4']}

setup(
    app=APP,
    name='Roastery',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
