"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Rosetta.py']
DATA_FILES = []
OPTIONS = {'iconfile':'Icons/icon.icns',
			'includes': ['sip','PyQt4']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
